// Lyrics and Chords extension for Gig Performer by @rank13

#include <vector>
#include <string>

// List of panels: the names that appear in the GP UI
std::vector<std::string> panelNames = {"Global Panel"};

// XML for the default included panels
std::vector<std::string> panelXML = { 
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
"<RACKUNIT size=\"10\" style=\"1024\" color=\"ff1b1b1b\" ver=\"5.0\">"
"  <WIDGET type=\"2\" style=\"1\" x=\"0.6526515151515152\" y=\"0.4911894273127753\""
"          width=\"0.0856060606060606\" height=\"0.973568281938326\" caption=\"Page Scroll\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.1294117647058824\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"15474\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\""
"          backPlate=\"11\" backPlateVisible=\"0\" invertMIDI=\"0\" displayRange=\"2\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_SCROLL\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.5704545454545454\" y=\"0.6277533039647577\""
"          width=\"0.09848484848484848\" height=\"0.4801762114537445\" caption=\"Page Down\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.2168674698795181\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\""
"          backPlate=\"7\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_DOWN\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.4727272727272727\" y=\"0.6277533039647577\""
"          width=\"0.09848484848484848\" height=\"0.4801762114537445\" caption=\"Page Up\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.2168674698795181\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\""
"          backPlate=\"7\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_UP\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.5204545454545455\" y=\"0.1519823788546255\""
"          width=\"0.1606060606060606\" height=\"0.2070484581497797\" caption=\"Lyrics/Chords\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"1\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.25\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.06704545454545455\" y=\"0.1519823788546255\""
"          width=\"0.09772727272727273\" height=\"0.2070484581497797\" caption=\"Window\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"1\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.2553191489361702\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"2\" style=\"1\" x=\"0.3700757575757576\" y=\"0.486784140969163\""
"          width=\"0.0856060606060606\" height=\"0.973568281938326\" caption=\"List Scroll\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.1294117647058824\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"15474\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\""
"          backPlate=\"11\" backPlateVisible=\"0\" invertMIDI=\"0\" displayRange=\"2\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_SONG_SCROLL\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.06780303030303031\" y=\"0.6497797356828194\""
"          width=\"0.1007575757575758\" height=\"0.5154185022026432\" caption=\"Open/Close\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3707865168539326\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\""
"          backPlate=\"11\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_OPEN\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.4189393939393939\" y=\"0.4911894273127753\""
"          width=\"0.01363636363636364\" height=\"0.9647577092511013\" caption=\"\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.08021390374331551\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3a3a3a\" outlineColor=\"f5f5f5\""
"          outlineRound=\"5\" outlineThick=\"10\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.8859848484848485\" y=\"0.4911894273127753\""
"          width=\"0.01439393939393939\" height=\"0.9647577092511013\" caption=\"\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.08021390374331551\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3a3a3a\" outlineColor=\"f5f5f5\""
"          outlineRound=\"5\" outlineThick=\"10\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.9429323968393327\" y=\"0.5076530612244898\""
"          width=\"0.1018437225636523\" height=\"0.8724489795918368\" caption=\"Note: This panel must be in the global rackspace\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"1\""
"          widgetIgnoresMouse=\"1\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.06432748538011696\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"0\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"18.0\" textPos=\"33\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"18\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.1378787878787879\" y=\"0.4911894273127753\""
"          width=\"0.01363636363636364\" height=\"0.9647577092511013\" caption=\"\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.08021390374331551\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3a3a3a\" outlineColor=\"f5f5f5\""
"          outlineRound=\"5\" outlineThick=\"10\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.2871212121212121\" y=\"0.6277533039647577\""
"          width=\"0.09848484848484848\" height=\"0.4801762114537445\" caption=\"Next Song\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.2168674698795181\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\""
"          backPlate=\"7\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_NEXT\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.1886363636363636\" y=\"0.6277533039647577\""
"          width=\"0.09848484848484848\" height=\"0.4801762114537445\" caption=\"Prev Song\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.2168674698795181\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\""
"          backPlate=\"7\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_PREV\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.2393939393939394\" y=\"0.1519823788546255\""
"          width=\"0.1606060606060606\" height=\"0.2070484581497797\" caption=\"Song List\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"1\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.25\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.7393939393939394\" y=\"0.6497797356828194\""
"          width=\"0.1\" height=\"0.5154185022026432\" caption=\"Play/Pause\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3707865168539326\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\""
"          backPlate=\"11\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_AUTOSCROLL_PLAY\" enableOSC=\"0\" invertOSC=\"0\""
"          groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.8337121212121212\" y=\"0.6255506607929515\""
"          width=\"0.075\" height=\"0.4757709251101321\" caption=\"Reset\" captionIncludesAttribute=\"0\""
"          hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\" widgetIgnoresMouse=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.212962962962963\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"0.0\""
"          backPlate=\"7\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_AUTOSCROLL_RESET\" enableOSC=\"0\" invertOSC=\"0\""
"          groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.7848484848484848\" y=\"0.1519823788546255\""
"          width=\"0.1606060606060606\" height=\"0.2070484581497797\" caption=\"Autoscroll\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"1\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.25\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" nodeId=\"0\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"</RACKUNIT>"
};