// Lyrics and Chords extension for Gig Performer by @rank13

#include <vector>
#include <string>

// List of panels: the names that appear in the GP UI
std::vector<std::string> panelNames = {"Global Panel"};

// XML for the default included panels
std::vector<std::string> panelXML = { 
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
"<RACKUNIT size=\"10\" style=\"1024\" color=\"ff1b1b1b\" ver=\"4.199999809265137\">"
"  <WIDGET type=\"2\" style=\"1\" x=\"0.6730612244897959\" y=\"0.490521327014218\""
"          width=\"0.08571428571428572\" height=\"0.9715639810426541\" caption=\"Page Scroll\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.1294117647058824\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"15474\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"0.0\""
"          backPlate=\"11\" backPlateVisible=\"0\" invertMIDI=\"0\" displayRange=\"2\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_SCROLL\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.5914285714285714\" y=\"0.6279620853080569\""
"          width=\"0.09877551020408164\" height=\"0.4786729857819905\" caption=\"Page Down\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.2168674698795181\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"0.0\""
"          backPlate=\"7\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_DOWN\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.493469387755102\" y=\"0.6279620853080569\""
"          width=\"0.09877551020408164\" height=\"0.4786729857819905\" caption=\"Page Up\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.2168674698795181\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"0.0\""
"          backPlate=\"7\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_UP\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.5408163265306123\" y=\"0.1516587677725119\""
"          width=\"0.1608163265306123\" height=\"0.2085308056872038\" caption=\"Lyrics/Chords\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"1\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.25\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.07673469387755102\" y=\"0.1516587677725119\""
"          width=\"0.1175510204081633\" height=\"0.2085308056872038\" caption=\"Window\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"1\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.2727272727272727\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"2\" style=\"1\" x=\"0.3906122448979592\" y=\"0.485781990521327\""
"          width=\"0.08571428571428572\" height=\"0.9715639810426541\" caption=\"List Scroll\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.1294117647058824\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"15474\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"0.0\""
"          backPlate=\"11\" backPlateVisible=\"0\" invertMIDI=\"0\" displayRange=\"2\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_SONG_SCROLL\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.07714285714285714\" y=\"0.6516587677725119\""
"          width=\"0.1004081632653061\" height=\"0.5165876777251185\" caption=\"Open/Close\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3707865168539326\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"1.0\""
"          backPlate=\"11\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_OPEN\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.4395918367346939\" y=\"0.4928909952606635\""
"          width=\"0.01387755102040816\" height=\"0.966824644549763\" caption=\"\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.08021390374331551\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3a3a3a\" outlineColor=\"f5f5f5\""
"          outlineRound=\"5\" outlineThick=\"10\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.7277551020408163\" y=\"0.4928909952606635\""
"          width=\"0.01387755102040816\" height=\"0.966824644549763\" caption=\"\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.08021390374331551\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3a3a3a\" outlineColor=\"f5f5f5\""
"          outlineRound=\"5\" outlineThick=\"10\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.8644897959183674\" y=\"0.5071090047393365\""
"          width=\"0.2579591836734694\" height=\"0.8720379146919431\" caption=\"Note: This panel must be in the global rackspace\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"1\""
"          widgetIgnoresMouse=\"1\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.06521739130434782\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"0\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"26.0\" textPos=\"33\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"26\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.1587755102040816\" y=\"0.4928909952606635\""
"          width=\"0.01387755102040816\" height=\"0.966824644549763\" caption=\"\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.08021390374331551\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"1.0\""
"          backPlate=\"10\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\""
"          updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3a3a3a\" outlineColor=\"f5f5f5\""
"          outlineRound=\"5\" outlineThick=\"10\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.3073469387755102\" y=\"0.6279620853080569\""
"          width=\"0.09877551020408164\" height=\"0.4786729857819905\" caption=\"Next Song\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.2168674698795181\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"0.0\""
"          backPlate=\"7\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_NEXT\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"10\" x=\"0.2093877551020408\" y=\"0.6279620853080569\""
"          width=\"0.09877551020408164\" height=\"0.4786729857819905\" caption=\"Prev Song\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          widgetIgnoresMouse=\"0\" overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.2168674698795181\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"0.0\""
"          backPlate=\"7\" backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\""
"          ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\""
"          directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\" directedOSCPort=\"9001\""
"          directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\""
"          widgetDirectedMaxIntValue=\"127\" widgetDirectedMinDoubleValue=\"0.0\""
"          widgetDirectedMaxDoubleValue=\"1.0\" widgetDirectedStringListValue=\"T2ZmCk9u\""
"          widgetHandle=\"GPLC_PREV\" enableOSC=\"0\" invertOSC=\"0\" groupName=\"\""
"          widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\" updateOnActivateRackspace=\"0\""
"          setDefaultDoubleClickResetValue=\"0.0\" globalAssignedParameterNumber=\"-1\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"1\" btnRadioGroupIndex=\"0\""
"          btnRespondsToButtonOff=\"1\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.26\" y=\"0.1516587677725119\" width=\"0.1608163265306123\""
"          height=\"0.2085308056872038\" caption=\"Song List\" captionIncludesAttribute=\"0\""
"          hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\" widgetIgnoresMouse=\"1\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.25\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" textColor=\"ffffffff\" widgetValue=\"1.0\" backPlate=\"10\""
"          backPlateVisible=\"1\" invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\""
"          followHardware=\"0\" relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"T2ZmCk9u\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          globalAssignedParameterNumber=\"-1\" bckgColor=\"ff3c3c3c\" outlineColor=\"808080\""
"          outlineRound=\"4\" outlineThick=\"2\" fontSize=\"15.0\" textPos=\"36\""
"          usesDimming=\"1.0\">"
"        <FONTPROPERTIES FontName=\"&lt;Sans-Serif&gt;\" FontHeight=\"15\" Bold=\"0\" Italic=\"0\""
"                    Underlined=\"0\"/>"
"  </WIDGET>"
"</RACKUNIT>"
};